spring:
  application:
    name: blogsite-api-gateway

  zipkin:
    enabled: true
    base-url: ${ZIPKIN_SERVER:http://localhost:9411/}

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: blogsite-blog-service
          uri: lb://blogsite-blog-service
          predicates:
            - Path=/api/v1.0/blogsite/blogs/**
        - id: blogsite-user-service
          uri: lb://blogsite-user-service
          predicates:
            - Path=/api/v1.0/blogsite/user/**

server:
  port: ${port:8080}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://blogsite-service-registry:8081/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
